"""Render capsules into agent-consumable formats.

Output targets in v0.1:
  - claude     -> CLAUDE.md
  - codex      -> AGENTS.md (also used by Codex CLI and various agent tools)
  - agents     -> AGENTS.md (alias of codex)
  - github     -> markdown body suitable for a GitHub issue / PR comment
  - prompt     -> a single plain-text prompt (no markdown chrome)

Each renderer takes the composed capsule list (already topologically sorted)
and produces a single string. The shape is opinionated: top-level orientation,
per-capsule sections, then a final "Next steps" block lifted from handoff.
"""

from __future__ import annotations

from typing import Callable

from capsule.loader import LoadedCapsule
from capsule.schema import Capsule

Target = str  # "claude" | "codex" | "agents" | "github" | "prompt"


def render(target: Target, capsules: list[LoadedCapsule]) -> str:
    renderer = _RENDERERS.get(target)
    if renderer is None:
        raise ValueError(
            f"unknown bundle target '{target}'. Known: {', '.join(_RENDERERS)}"
        )
    return renderer(capsules)


def _render_claude(capsules: list[LoadedCapsule]) -> str:
    return _render_markdown(capsules, title="CLAUDE.md", framing=_CLAUDE_FRAMING)


def _render_codex(capsules: list[LoadedCapsule]) -> str:
    return _render_markdown(capsules, title="AGENTS.md", framing=_CODEX_FRAMING)


def _render_github(capsules: list[LoadedCapsule]) -> str:
    return _render_markdown(capsules, title=None, framing=_GITHUB_FRAMING)


def _render_prompt(capsules: list[LoadedCapsule]) -> str:
    parts: list[str] = [_PROMPT_FRAMING.strip(), ""]
    for lc in capsules:
        parts.append(f"## Capsule: {lc.name} v{lc.capsule.version}")
        parts.append(_summary(lc.capsule))
        if lc.capsule.agent.summary_for_ai:
            parts.append("AI orientation:")
            parts.append(lc.capsule.agent.summary_for_ai.strip())
        if lc.capsule.agent.avoid:
            parts.append("Avoid:")
            for a in lc.capsule.agent.avoid:
                parts.append(f"  - {a}")
        parts.append("")
    _append_handoff_block(parts, capsules)
    return "\n".join(parts).rstrip() + "\n"


def _render_markdown(
    capsules: list[LoadedCapsule],
    *,
    title: str | None,
    framing: str,
) -> str:
    out: list[str] = []
    if title:
        out.append(f"<!-- {title} generated by capsule bundle -->")
        out.append("")
    out.append(framing.strip())
    out.append("")
    out.append("## Capsules in scope")
    out.append("")
    for lc in capsules:
        c = lc.capsule
        out.append(f"- **{c.name}** v{c.version} — {c.purpose.summary.strip().splitlines()[0]}")
    out.append("")

    for lc in capsules:
        out.extend(_capsule_section(lc))

    _append_handoff_block(out, capsules)
    return "\n".join(out).rstrip() + "\n"


def _capsule_section(lc: LoadedCapsule) -> list[str]:
    c = lc.capsule
    s: list[str] = []
    s.append(f"## {c.name} (v{c.version}, {c.type})")
    s.append("")
    s.append(c.purpose.summary.strip())
    s.append("")
    if c.purpose.owns:
        s.append("**Owns**")
        for item in c.purpose.owns:
            s.append(f"- {item}")
        s.append("")
    if c.purpose.does_not_own:
        s.append("**Does not own**")
        for item in c.purpose.does_not_own:
            s.append(f"- {item}")
        s.append("")
    if c.agent.summary_for_ai:
        s.append("**AI orientation**")
        s.append("")
        s.append(c.agent.summary_for_ai.strip())
        s.append("")
    if c.agent.avoid:
        s.append("**Avoid**")
        for a in c.agent.avoid:
            s.append(f"- {a}")
        s.append("")
    if c.agent.extension_points:
        s.append("**Extension points**")
        for ep in c.agent.extension_points:
            s.append(f"- `{ep.id}` at `{ep.where}` — {ep.contract.strip()}")
        s.append("")
    if c.interfaces.provides:
        s.append("**Provides**")
        for p in c.interfaces.provides:
            s.append(f"- `{p.kind}:{p.name}`" + (f" — {p.description}" if p.description else ""))
        s.append("")
    if c.interfaces.requires:
        s.append("**Requires**")
        for r in c.interfaces.requires:
            tag = f"`{r.kind}:{r.name}`"
            if r.from_capsule:
                tag += f" from `{r.from_capsule}`"
                if r.version:
                    tag += f" ({r.version})"
            s.append(f"- {tag}")
        s.append("")
    if c.verification.invariants:
        s.append("**Invariants (must always hold)**")
        for inv in c.verification.invariants:
            s.append(f"- {inv}")
        s.append("")
    return s


def _append_handoff_block(out: list[str], capsules: list[LoadedCapsule]) -> None:
    handoffs = [(lc.name, lc.capsule.handoff) for lc in capsules if lc.capsule.handoff]
    if not handoffs:
        return
    out.append("## Handoff: pick up where the last agent left off")
    out.append("")
    for name, h in handoffs:
        out.append(f"### {name}")
        out.append("")
        out.append(f"**Objective.** {h.objective.strip()}")
        out.append("")
        if h.completed:
            out.append("**Completed**")
            for item in h.completed:
                out.append(f"- {item}")
            out.append("")
        if h.remaining:
            out.append("**Remaining**")
            for item in h.remaining:
                out.append(f"- {item}")
            out.append("")
        if h.next_agent_should:
            out.append("**Next agent should**")
            for item in h.next_agent_should:
                out.append(f"- {item}")
            out.append("")
        if h.do_not_touch:
            out.append("**Do not touch**")
            for item in h.do_not_touch:
                out.append(f"- {item}")
            out.append("")
        if h.open_questions:
            out.append("**Open questions**")
            for item in h.open_questions:
                out.append(f"- {item}")
            out.append("")


def _summary(c: Capsule) -> str:
    return c.purpose.summary.strip()


_CLAUDE_FRAMING = """
This file was generated by `capsule bundle --for claude`. It describes the
subsystems Claude Code is allowed to reason about in this workspace.

Read every section before editing code. Respect each capsule's "Does not own"
and "Avoid" lists — those are hard boundaries, not suggestions. When you make
changes, run `capsule verify` and update the handoff block before stopping.
""".strip()

_CODEX_FRAMING = """
This file was generated by `capsule bundle --for codex`. It is the
agent-facing contract for the subsystems in this workspace.

Before you change code:
  1. Read the relevant capsule section in full.
  2. Confirm your task does not violate any "Does not own" or "Avoid" entry.
  3. After changes, run `capsule verify` and report results.
  4. If you leave work in progress, update the handoff block.
""".strip()

_GITHUB_FRAMING = """
**Context capsule (auto-generated by `capsule bundle --for github`).**

Use this as the shared work-state for whoever — human or agent — picks up
this issue next. The handoff block at the bottom is the source of truth for
what is in progress.
""".strip()

_PROMPT_FRAMING = """
You are about to work on a software system that has been packaged as one or
more capsules. Each capsule below tells you what a subsystem is, what it
promises, what it must not do, and where the last agent left off.

Rules:
- Respect every "Does not own" and "Avoid" item.
- Run `capsule verify` after changes.
- Update the handoff block before stopping.
""".strip()


_RENDERERS: dict[str, Callable[[list[LoadedCapsule]], str]] = {
    "claude": _render_claude,
    "codex": _render_codex,
    "agents": _render_codex,
    "github": _render_github,
    "prompt": _render_prompt,
}
